KSNIFF_ZIP_FILE_NAME: ksniff.zip
CLIENT_NS: default
CLIENT_POD: wemeet-state-0
SERVER_NS: default
SERVER_POD: wemeet-lapetus-0
PORT: 9098
PKG_BYTE_LEN: 1024
PKG_COUNT: 5
PROTOCOL: udp
MODE: pod
MULTI_SERVER_NS: default
MULTI_SERVER_POD: wemeet-lapetus
